CREATE DATABASE IF NOT EXISTS unimarket;
USE unimarket;

CREATE TABLE IF NOT EXISTS categories (
  categoryID SMALLINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS postCategoryDetails (
  postID INT NOT NULL,
  categoryID SMALLINT NOT NULL
);


CREATE TABLE IF NOT EXISTS postImageDetails (
  postID INT NOT NULL,
  fileName VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS posts (
  postID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  userID VARCHAR(32) NOT NULL,
  title VARCHAR(50) NOT NULL,
  description VARCHAR(100) NOT NULL,
  quantity TINYINT NOT NULL,
  price INT NOT NULL,
  availableFrom SMALLINT NOT NULL,
  availableTo SMALLINT NOT NULL,
  active TINYINT(1) NOT NULL
);


CREATE TABLE IF NOT EXISTS userImageDetails (
  userID VARCHAR(32) NOT NULL,
  fileName VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS users (
  userID VARCHAR(32) NOT NULL PRIMARY KEY,
  userKey VARCHAR(32) NOT NULL,
  name VARCHAR(50) NOT NULL,
  lastname VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(64) NOT NULL
);